---

modules:
  icmp:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: ip6
      ip_protocol_fallback: true

  ssh:
    prober: tcp
    timeout: 3s
    tcp:
      query_response:
      - expect: "^SSH-2.0-"

  https:
    prober: http
    timeout: 3s
    http:
      preferred_ip_protocol: ip6
      ip_protocol_fallback: true
      fail_if_not_ssl: true
